gold/urls.py
from django.conf.urls import url

from . import views
app_name = 'gold'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add_the_income/$', views.add_the_income, name='add_the_income'),
    url(r'^history/$', views.history, name='history'),
]

mymoney/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^gold/', include('gold.urls')),
    url(r'^admin/', admin.site.urls),
]

gold/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone


class Income(models.Model):
    income_text     = models.CharField(max_length=200)
    money_in_text   = models.CharField(max_length=20)
    expenses_text   = models.CharField(max_length=200)
    money_out_text  = models.CharField(max_length=20)
    remaining       = models.FloatField(default=0)
    pub_date        = models.DateTimeField('date published')
    
   
    def __str__(self):
        return self.income_text
        return self.money_in_text
        return self.expenses_text
        return self.money_in_text
       

gold/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Income 
from django.utils import timezone

class IndexView(generic.ListView):
    template_name = 'gold/index.html'
    context_object_name = 'latest_income_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Income.objects.order_by('-pub_date')[:5]
        
def add_the_income(request):
     try:
         the_last = Income.objects.order_by('-id')[0].remaining
     except:
         the_last =0
     latest_income_list = Income.objects.order_by('-pub_date')[:5]
     if request.POST['bank'] == "in":
         income = Income(income_text=request.POST['add_income'],money_in_text=request.POST['add_money'],remaining=the_last+int(request.POST['add_money']),pub_date=timezone.now())
         income.save()
     else:
         expenses = Income(expenses_text=request.POST['add_income'],money_out_text=request.POST['add_money'], remaining=the_last-int(request.POST['add_money']),pub_date=timezone.now())
         expenses.save()
     context = {'latest_income_list':latest_income_list}
     return render(request,'gold/index.html',context)

def history(request):
    latest_income_list = Income.objects.order_by('pub_date')[:500]
    context = {'latest_income_list':latest_income_list}
    return render(request,'gold/history.html',context)

gold/templates/gold/history.html
<style>
table, th, td {
    border: 3px solid black;
    border-collapse: collapse;
}
</style>
<body bgcolor="orange">
<br>
<br>

<table align="center" style="width:100%">
<tr style="font-size:28px">
    <th>รายรับ</th>
    <th>จำนวนเงิน</th> 
    <th>ยอดคงเหลือ</th>
    <th>วัน / เดือน / ปี</th>
</tr>
{% if latest_income_list %}
   {% for income in latest_income_list  %}
   {% if income.income_text != "" %} 
   	<tr style="background-color:green;" align="center" ><td style="font-size:28px;">{{ income.income_text }}</td>
        <td style="font-size:28px;">{{ income.money_in_text }}</td>
        <td style="font-size:28px;">{{  income.remaining }}</td>
        <td style="font-size:28px;">{{ income.pub_date }}</td></tr> 
{% elif income.income_text == "" %}
         <tr style="background-color:red;" align="center" ><td style="font-size:28px;">{{ income.expenses_text }}</td> 
         <td style="font-size:28px;">{{ income.money_out_text }}</td>
         <td style="font-size:28px;">{{  income.remaining }}</td>
         <td style="font-size:28px;">{{ income.pub_date }}</td></tr>
    {% endif %}
   {% endfor %}
{% endif %}
</table>
</body>

gold/templates/gold/index.html
<style>
table, th, td {
    border: 3px solid black;
    border-collapse: collapse;
}
</style>
<body bgcolor="orange">
<br>
<br>

<table align="center" style="width:100%">
<tr style="font-size:28px">
    <th>รายรับ</th>
    <th>จำนวนเงิน</th> 
    <th>ยอดคงเหลือ</th>
    <th>วัน / เดือน / ปี</th>
</tr>
{% if latest_income_list %}
   {% for income in latest_income_list  %}
   {% if income.income_text != "" %} 
   	<tr style="background-color:green;" align="center" ><td style="font-size:28px;">{{ income.income_text }}</td>
        <td style="font-size:28px;">{{ income.money_in_text }}</td>
        <td style="font-size:28px;">{{  income.remaining }}</td>
        <td style="font-size:28px;">{{ income.pub_date }}</td></tr> 
{% elif income.income_text == "" %}
   <tr style="background-color:red;" align="center" ><td style="font-size:28px;">{{ income.expenses_text }}</td> 
   <td style="font-size:28px;">{{ income.money_out_text }}</td>
   <td style="font-size:28px;">{{  income.remaining }}</td>
   <td style="font-size:28px;">{{ income.pub_date }}</td></tr>
    {% endif %}
   {% endfor %}
{% endif %}
</table>
<br>
 <form action="{% url 'gold:history' %}" method="post">
     {% csrf_token %}
     <input type="submit" value="ประวัติ">
</form>
 <form action="{% url 'gold:add_the_income' %}" method="post">
     {% csrf_token %}
       <input type="radio" name="bank" value="in"><b style="font-size:20px;"> รายรับ<br></b>
       <input type="radio" name="bank" value="out" ><b style="font-size:20px;"> รายจ่าย<br></b> 
       <input type="text" name="add_income">
        <p><b style="font-size:20px;">จำนวนเงิน</p></b>
       <input type="text" name="add_money"><br>
<br>
    <input type="submit" value="เพิ่ม">
    </form>
</body>